ALTER TABLE meta_nutrientes
ALTER COLUMN fibras SET DEFAULT 30,
ALTER COLUMN colesterol SET DEFAULT 300,
ALTER COLUMN sodio SET DEFAULT 1500,
ALTER COLUMN potassio SET DEFAULT 3500,
ALTER COLUMN ferro SET DEFAULT 10,
ALTER COLUMN calcio SET DEFAULT 1000,
ALTER COLUMN zinco SET DEFAULT 10,
ALTER COLUMN vitamina_c SET DEFAULT 90,
ALTER COLUMN magnesio SET DEFAULT 350;

ALTER TABLE users_info
ALTER COLUMN altura TYPE NUMERIC(3,0)

